"""The contract-pinned lake indexes rebuild command (runner packaging).

Shape pinned by the derived-layout contract:
``lake indexes rebuild --root <ORCA_DATA_ROOT> --target
availability|derived_retrieval|all --prove-rebuildability`` — the semantics
are the contract; the argparse runner is the incumbent CLI packaging
(consumption seam contract, Rebuild Command Binding).

Modes:

- **rebuild** (default): regenerate the requested index tier(s) from committed
  material. ``availability`` delegates to ``DataLakeRoot.rebuild_availability``;
  ``derived_retrieval`` wipes and rewrites the object-level views under a
  fresh generation stamp.
- **--prove-rebuildability**: verification. ``derived_retrieval`` is proven
  read-only — every stored view is regenerated under the stamps its stored
  manifest recorded and byte-compared (a rebuild is never compared against
  itself). ``availability`` is proven by before/after byte comparison around
  an in-place rebuild (mutation-to-truth): any drift means the stored index
  was smuggling non-regenerable or stale state and is reported as a failure.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from data_lake.derived_retrieval_views import (
    prove_derived_retrieval_rebuildability,
    rebuild_derived_retrieval,
)
from data_lake.root import DataLakeRoot, DataLakeRootError


def _availability_snapshot(root: DataLakeRoot) -> dict[str, bytes]:
    availability_dir = root.path / "indexes" / "availability"
    if not availability_dir.is_dir():
        return {}
    return {
        entry.name: entry.read_bytes()
        for entry in sorted(availability_dir.iterdir())
        if entry.is_file()
    }


def _rebuild_availability(root: DataLakeRoot, *, prove: bool) -> dict:
    if not prove:
        return {"status": "rebuilt", "entry_count": root.rebuild_availability()}
    before = _availability_snapshot(root)
    entry_count = root.rebuild_availability()
    after = _availability_snapshot(root)
    drifted = sorted(
        name
        for name in set(before) | set(after)
        if before.get(name) != after.get(name)
    )
    return {
        "status": "proven" if not drifted else "failed",
        "entry_count": entry_count,
        "drifted_entries": drifted,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Rebuild or prove the rebuildability of the Data Lake index tiers "
            "(availability, derived_retrieval object-level views)."
        )
    )
    parser.add_argument(
        "--root",
        "--data-root",
        dest="data_root",
        help="Explicit Orca data root path (falls back to ORCA_DATA_ROOT).",
    )
    parser.add_argument(
        "--target",
        choices=("availability", "derived_retrieval", "all"),
        default="all",
        help="Which index tier to rebuild or prove (default: all).",
    )
    parser.add_argument(
        "--prove-rebuildability",
        action="store_true",
        help=(
            "Verify instead of build: fail when any stored index entry cannot be "
            "regenerated byte-identically from committed material."
        ),
    )
    args = parser.parse_args(argv)

    report: dict = {"target": args.target, "prove": args.prove_rebuildability}
    try:
        root = DataLakeRoot.resolve(explicit=args.data_root)
        statuses: list[str] = []
        if args.target in ("availability", "all"):
            availability = _rebuild_availability(root, prove=args.prove_rebuildability)
            report["availability"] = availability
            statuses.append(availability["status"])
        if args.target in ("derived_retrieval", "all"):
            if args.prove_rebuildability:
                derived = prove_derived_retrieval_rebuildability(root)
            else:
                derived = rebuild_derived_retrieval(root)
            report["derived_retrieval"] = derived
            statuses.append(derived["status"])
    except DataLakeRootError as exc:
        report["status"] = "error"
        report["error"] = str(exc)
        print(json.dumps(report, indent=2, sort_keys=True))
        return 2

    report["status"] = "ok" if all(s in {"rebuilt", "proven"} for s in statuses) else "failed"
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
