from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Mapping


class CaptureBodyClass(StrEnum):
    """Honest classification of a preserved capture body.

    There is deliberately NO positive ``CONTENT`` member: this guard can detect
    block/challenge shells and emptiness, but it cannot certify that an arbitrary
    body IS the real source. The most a body earns is ``CONTENT_UNVERIFIED``.
    """

    BLOCK_SHELL = "block_shell"
    EMPTY = "empty"
    CONTENT_UNVERIFIED = "content_unverified"


@dataclass(frozen=True)
class CaptureBodyClassification:
    classification: CaptureBodyClass
    signal: str | None
    detail: str


# High-confidence interstitial / bot-wall body signatures, matched as lowercased
# substrings against the decoded body prefix. Kept conservative: only well-known
# challenge/block markers appear here. Anything else stays CONTENT_UNVERIFIED
# rather than being claimed as real source content. Over-flagging real content as
# a block_shell is the safe error direction (it under-claims, body is still
# preserved); under-flagging a shell as content is the dangerous fake-pass.
_BODY_BLOCK_SIGNATURES: tuple[tuple[str, str], ...] = (
    ("just a moment", "cloudflare_interstitial"),
    ("checking your browser", "cloudflare_interstitial"),
    ("cdn-cgi/challenge-platform", "cloudflare_challenge"),
    ("challenge-platform", "cloudflare_challenge"),
    ("attention required", "cloudflare_block"),
    ("access denied", "generic_access_denied"),
    ("request blocked", "generic_request_blocked"),
    ("the request is blocked", "generic_request_blocked"),
    ("you have been blocked", "generic_block"),
    ("verify you are human", "captcha_human_check"),
    ("are you a robot", "captcha_human_check"),
    ("recaptcha", "recaptcha"),
    ("g-recaptcha", "recaptcha"),
    ("hcaptcha", "hcaptcha"),
    ("px-captcha", "perimeterx"),
    ("access to this page has been denied", "perimeterx"),
    ("perimeterx", "perimeterx"),
    ("datadome", "datadome"),
    ("incapsula", "incapsula"),
    ("_incapsula_resource", "incapsula"),
    ("imperva", "imperva"),
    ("sucuri website firewall", "sucuri"),
    ("aws waf", "aws_waf"),
    ("generated by cloudfront", "aws_cloudfront"),
    ("reference #", "akamai_reference"),
    ("unusual traffic", "google_unusual_traffic"),
)

# High-confidence block signals carried on response headers.
_HEADER_BLOCK_SIGNATURES: tuple[tuple[str, str], ...] = (
    ("cf-mitigated", "cloudflare_mitigated"),
    ("x-datadome", "datadome_header"),
    ("x-datadome-cid", "datadome_header"),
    ("x-amzn-waf-action", "aws_waf_header"),
    ("x-iinfo", "imperva_header"),
    ("x-sucuri-id", "sucuri_header"),
    ("x-sucuri-cache", "sucuri_header"),
)

_BODY_SCAN_BYTES = 65536
_ENCODED_BODY_ENCODINGS = frozenset({"br", "compress", "deflate", "gzip", "zstd"})


def classify_capture_body(
    *,
    status: int,
    headers: Mapping[str, str] | None,
    body: bytes,
) -> CaptureBodyClassification:
    """Classify a preserved capture body as block-shell, empty, or unverified content.

    This is a conservative anti-fake-pass guard, not a content validator. It NEVER
    asserts that a body IS the real source. The best result is
    ``CONTENT_UNVERIFIED`` -- "no known block/challenge signature was detected and
    a non-empty body was preserved; the body is not independently certified as the
    source." Only high-confidence interstitial / bot-wall signatures yield
    ``BLOCK_SHELL``.

    ``status`` is accepted for caller symmetry but is intentionally NOT used to
    decide the body class: HTTP-status posture (e.g. a 403 access_failed) is owned
    by the runner and combined with this body classification separately.
    """
    _ = status  # status posture is owned by the runner, not this body guard

    if not body or not body.strip():
        return CaptureBodyClassification(
            classification=CaptureBodyClass.EMPTY,
            signal=None,
            detail="preserved body is empty or whitespace-only",
        )

    content_encoding = _header_value(headers, "content-encoding")

    if headers:
        lowered_header_keys = {str(key).lower() for key in headers.keys()}
        for header_key, signal in _HEADER_BLOCK_SIGNATURES:
            if header_key in lowered_header_keys:
                return CaptureBodyClassification(
                    classification=CaptureBodyClass.BLOCK_SHELL,
                    signal=signal,
                    detail=f"response header '{header_key}' indicates a bot-mitigation / challenge response",
                )

    if content_encoding and any(
        encoding in _ENCODED_BODY_ENCODINGS for encoding in _header_tokens(content_encoding)
    ):
        return CaptureBodyClassification(
            classification=CaptureBodyClass.CONTENT_UNVERIFIED,
            signal="encoded_body_uninspectable",
            detail=(
                f"response body uses Content-Encoding '{content_encoding}'; preserved bytes are "
                "not decoded, so body block/challenge signature inspection is limited"
            ),
        )

    scanned = min(len(body), _BODY_SCAN_BYTES)
    text_prefix = body[:_BODY_SCAN_BYTES].decode("latin-1").lower()
    for needle, signal in _BODY_BLOCK_SIGNATURES:
        if needle in text_prefix:
            return CaptureBodyClassification(
                classification=CaptureBodyClass.BLOCK_SHELL,
                signal=signal,
                detail=f"body matched block/challenge signature '{needle}' ({signal})",
            )

    return CaptureBodyClassification(
        classification=CaptureBodyClass.CONTENT_UNVERIFIED,
        signal=None,
        detail=(
            f"no known block/challenge signature detected in first {scanned} bytes; "
            "body preserved but not certified as source content"
        ),
    )


def _header_value(headers: Mapping[str, str] | None, name: str) -> str | None:
    if not headers:
        return None
    target = name.lower()
    for key, value in headers.items():
        if str(key).lower() == target:
            return str(value)
    return None


def _header_tokens(value: str) -> set[str]:
    return {
        token.strip().lower()
        for part in value.split(",")
        for token in part.split(";")
        if token.strip()
    }


__all__ = [
    "CaptureBodyClass",
    "CaptureBodyClassification",
    "classify_capture_body",
]
